### ISSUE TITLE
Enable Keepass HTTP Server Unavailable (again)

### ISSUE THREAD

**Issue by mattnewham** [MacPass/MacPassHTTP#11]
Hey

Just compiled as per your instructions, running Version 0.5.1 (2556) and mpplugin is correctly located in the Application Support folder, however the option for Keepass HTTP is still greyed out. I have restarted the app multiple times to no avail.

Any advice on what I could be doing wrong? The plugin build was successful according to the output and is 1.4MB

**Comment by mstarke** [comment]
This is something I thought would be obvious, but isn't. There's no binary release of MacPass able to load Plugins. You need to compile MacPass as well!

**Comment by mstarke** [comment]
Simple check:

If you see a KeePassHTTP checkbox in the "Integration" Tab and/or no "Plugins" Tab, you're running a version of MacPass without plugin support (e.g. 0.5.1)

**Comment by mattnewham** [comment]
That fixed it! Thanks Michael
