### ISSUE TITLE
Can't find the plugin after successful build

### ISSUE THREAD

**Issue by denbue** [MacPass/MacPassHTTP#14]
I successfully executed the build as you instructed two times now but I can't find the plugin in the folder "~/Library/Application Support/MacPass/" afterwards neither does it show up in the App (the build and release version). here you can find the log of the terminal:  http://pastebin.com/raw/12GY12dn

**Comment by mstarke** [comment]
You've found a bug in the documentation as this just builds MacPass but not MacPassHTTP :)

I'll fix the Readme. Take a look at ad483043b19a449ad03367e3670ca0486beba74d to see what you need to do differently the third time (which – as we all know – is the charm ;) )
