### ISSUE TITLE
Release binary version

### ISSUE THREAD

**Issue by Nes-si** [MacPass/MacPassHTTP#15]
Could you publish binary for you new MacPass 0.6.1?

**Comment by Mirocow** [comment]
please

**Comment by foorb** [comment]
Yeah, this would be great.

**Comment by denbue** [comment]
Try this:

[MacPassHTTP.mpplugin.zip](https://github.com/MacPass/MacPassHTTP/files/142270/MacPassHTTP.mpplugin.zip)

It's working fine for me with 0.6.2.
- Make sure you check "load unsecure plugins" in MacPass Settings -> Plugins, close the program
- Move it the downloaded file to ~/Library/Application Support/MacPass/
- Start MacPass, check the plugins tab again

**Comment by kdoteu** [comment]
It worked but is we must trust you and your compiler that everything is right and nothing is changed;D 
so an offical release would be better

**Comment by Mirocow** [comment]
thx for 0.6.2. its work for build #12420

**Comment by robsalasco** [comment]
+1

**Comment by mstarke** [comment]
Here you go https://github.com/MacPass/MacPassHTTP/releases.
