### ISSUE TITLE
MacPassHTTTP does not bind to 127.0.0.1

### ISSUE THREAD

**Issue by sardaukar** [MacPass/MacPassHTTP#19]
I can telnet onto port 19455 on my mac from other stations on my LAN. Why is the bind not to localhost only? Motivated by https://github.com/pfn/keepasshttp/issues/258

**Comment by lenucksi** [comment]
:+1:

**Comment by sardaukar** [comment]
Yay!

**Comment by mstarke** [comment]
I did f**\* up 0.2 as it inverted the settings, fixed in 0.2.1
