### ISSUE TITLE
Build failed with error no visibile interface for KPKGroup and method addEntry

### ISSUE THREAD

**Issue by m1rc0** [MacPass/MacPassHTTP#20]
Hi, when building I get the following errors:

/Users/Mirco/Repos/MacPassHTTP/MacPassHTTP/MPHServerDelegate.m:128:20: error: no visible
      @interface for 'KPKGroup' declares the selector 'addEntry:'
    [document.root addEntry:configEntry];
     ~~~~~~~~~~~~~ ^~~~~~~~
/Users/Mirco/Repos/MacPassHTTP/MacPassHTTP/MPHServerDelegate.m:226:32: error: no visible
      @interface for 'KPKGroup' declares the selector 'addEntry:'
      [welf.queryDocument.root addEntry:entry];
       ~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~

Any suggestions what I'm doing wrong?

Thank you very much

**Comment by mstarke** [comment]
Checkout MacPass 0.6.x not the master, it's using a newer KeePassKit API

**Comment by mstarke** [comment]
I might actually add MacPass via Carthage as this then should resolve the dependency issues altogether in a nicer way than having to pull two repos

**Comment by mstarke** [comment]
And another reason to start to use git-flow ;)

**Comment by m1rc0** [comment]
Awesome, thank you very very much!

**Comment by mstarke** [comment]
You do know there's an actual binary release for the current version, right?

**Comment by m1rc0** [comment]
But not for the extension?

**Comment by mstarke** [comment]
Of course https://github.com/MacPass/MacPassHTTP/releases

**Comment by m1rc0** [comment]
Whops. :) 

Nah, but now it works and I learned something.
