### ISSUE TITLE
Problem with building the project

### ISSUE THREAD

**Issue by IvanTausan** [MacPass/MacPassHTTP#22]
Hello,

I am having a problem building this project. I did everything required to do so in readme (I hope at least). I had no issue building MacPass.

Issue happens in MPHServerDelegate.m

.../MacPassHTTP/MacPassHTTP/MPHServerDelegate.m:128:20: No visible @interface for 'KPKGroup' declares the selector 'addEntry:'

.../MacPassHTTP/MacPassHTTP/MPHServerDelegate.m:225:32: No visible @interface for 'KPKGroup' declares the selector 'addEntry:'

Any help in getting this built would be appreciated. Thank you.

**Comment by mstarke** [comment]
You did not check out tag of MacPass 0.6.2-alpha

There's a crucial line in the Readme:

```
git checkout 0.6.2-alpha
```

Or you could just use the [Release](https://github.com/MacPass/MacPassHTTP/releases/tag/0.2.1)

**Comment by IvanTausan** [comment]
That did the trick. Though I did build MacPass before HTTP plugin, I skipped that part thinking its not needed.
Ok so now I have the plugin, its in the default location like readme file indicated. However, it does not load in main MacPass app. I do not see it under "plugins" section.

**Comment by mstarke** [comment]
Take a look at the settings. At the top there is a checkbox, that is unchecked by default. Thus no unsigned plug-ins are loaded. Since you compiled the plugin without signing you need to check this box. After that the plugin should work.

**Comment by IvanTausan** [comment]
I did that first thing. Restarted MacPass few times. Rebuilt it from master once more... no idea why it does not work.

**Comment by mstarke** [comment]
You should use MacPass 0.6.2-alpha as well, newer versions bundle an incompatible `KeePassKit.framwork`. Did you check the logs for any complaints MacPass might put in there? Although you said the plugin is at the right location, can you check whether it's actually in `~/Library/Application Support/MacPass/`?
