### ISSUE TITLE
Export of an entry to another database

### ISSUE THREAD

**Issue by woyczek** [MacPass/MacPassHTTP#27]
Copy / paste, or export/import of a single entry.

My be really usefull to duplicate the keepasshttp authentication entry over multiple opened databases, and be a workaround for bug #8.

**Comment by mstarke** [comment]
Drag and Drop across Databases should work. You can drag the authentication entry from one DB to another one. If it doesn't it's a regression.

**Comment by mstarke** [comment]
I'm closing this as this is MacPass related as well as working in MacPass
