### ISSUE TITLE
MacPass not listening on port 19455

### ISSUE THREAD

**Issue by schoberw** [MacPass/MacPassHTTP#35]
I installed the precompiled versions as mentioned on this page. All looks good, plugin is here - with and without "Unsecure Plugins", with and without "remote connections". When starting MacPass I do not see it opening a listening socket:

```
schoberw@pc11:~$ netstat -an -p tcp | grep 19455
schoberw@pc11:~$
```

Firefox, Chrome cannot connect obviously. This is the case on my iMac and MBA both running Sierra 10.12.5. /var/log/system.log doesn't give any output on startup MacPass. 

Any inputs to move on welcome! Thanks!

**Comment by schoberw** [comment]
Build from source (thanks to slovdahl - I had a case sensitive git repo, too, but am not that experienced) and "load insecure Plugins" and voilà:

```
schoberw@pc11:~/git/MacPassHTTP$ netstat -an -p tcp | grep 19455
tcp6       0      0  ::1.19455              *.*                    LISTEN
tcp4       0      0  127.0.0.1.19455        *.*                    LISTEN
```

So it seems the binary build is not working on Sierra 10.12.5.

**Comment by mstarke** [comment]
The Binary build is not compatible with the current MacPass source or the continous release. You need to run the old 0.6.2 binary. If I get to it I'll add a nightly for MacPassHTTP as well to keep it in sync.

**Comment by greuff** [comment]
Please provide a build for MacPass-continuous.
