### ISSUE TITLE
Fix building on case-sensitive file systems

### ISSUE THREAD

**Issue by slovdahl** [MacPass/MacPassHTTP#36]
Would you be able to fix building MacPassHTTP by updating the MacPassHTTPKit dependency to a version that contains the fix in MacPass/KeePassHTTPKit#1?

**Comment by slovdahl** [comment]
Any update on this?

The latest available release of MacPassHTTP plugin (0.2.1) doesn't seem to work with the continuous builds of MacPass, so that's why I'd like to build a newer version of it.

**Comment by mstarke** [comment]
Added travis build setup for continuous build that includes the proposed fixes

**Comment by woyczek** [comment]
Le Fri, Sep 15, 2017 at 08:09:38PM +0000, Sebastian Lövdahl a écrit :
> Any update on this?
> 
> The latest available release of MacPassHTTP plugin (0.2.1) doesn't seem to work with the continuous builds of MacPass, so that's why I'd like to build a newer version of it.
> 
 
-- 
- Puis-je vous poser une question stupide ?
- Vous venez de le faire.
-- André Weil

Gaétan RYCKEBOER -- Message imprimé sur papier recycle 2.0

**Comment by mstarke** [comment]
@woyczek care to elaborate? :)
