### ISSUE TITLE
Can't connect to ChromeIPass and PassIFox, no service at 19455

### ISSUE THREAD

**Issue by p3v4x** [MacPass/MacPassHTTP#37]
Hi, 
I've downloaded MacPass 0.6.2 and MacPassHTTP 0.2.1. Installation went well, plugin was detected by MacPass, but no service is listening on port 19455. I thought that maybe firewall is preventing connection, but I've shut it down and no change. 
So I've checked if there is service listening on given port ( lsof -n -i4TCP:$PORT | grep LISTEN ) but nothing. Any hints what else to check? 

Thanks in advace.

**Comment by mstarke** [comment]
Did you download the 0.6.2 release or the continuous version of MacPass?

**Comment by p3v4x** [comment]
Continuous version of MacPass.

**Comment by mstarke** [comment]
There you have your problem. MacPassHTTP binary does not work with the continuous build, you need to build from source or wait till I supply a new release.

**Comment by p3v4x** [comment]
Thanks 👍
