### ISSUE TITLE
Needed to carthage bootstrap MacPass to build MacPassHTTP

### ISSUE THREAD

**Issue by Beej126** [MacPass/MacPassHTTP#4]
Just thought I'd leave a note for others that I found I needed to do the carthage bootstrap in the MacPass folder to successfully build MacPassHTTP (not indicated in install instructions).

**Comment by paulator** [comment]
Thank you. That solved my problem as well :+1: 
Nice work

**Comment by mstarke** [comment]
Fixed in e52b8aec35e1370e800197c19b739a703ed17f3b
