### ISSUE TITLE
The server does not work

### ISSUE THREAD

**Issue by wlatt1991** [MacPass/MacPassHTTP#40]
macOS Sierra 10.12.6
Safari 10.1.2
MacPASS 0.6.2
passafari v1.0.beta2

Log:
![image_2017-09-08_01-04-49](https://user-images.githubusercontent.com/16727848/30182879-ce1f7e58-9431-11e7-8082-3ee0b90ddc9f.png)

http://localhost:19455 does not work

**Comment by larslue** [comment]
Downgrading MacPass from the continous release build to 0.6.2-alpha did the job for me. I assume that MacPassHTTP is not yet compatible with the latest changes in MacPass

**Comment by wlatt1991** [comment]
Thank you! Working!

**Comment by mstarke** [comment]
MacPassHTTP continuous will work with MacPass continuous
