### ISSUE TITLE
Neither latest master nor continuous build works

### ISSUE THREAD

**Issue by slovdahl** [MacPass/MacPassHTTP#41]
I have tried the current continuous build, and I also tried building the plugin from source. The result is the same in both cases:
```
$ ./MacPass -v
2017-09-25 23:17:50.809 MacPass[17061:102862] No internal plugins found!
2017-09-25 23:17:50.813 MacPass[17061:102862] Preflight Error The bundle “MacPassHTTP” couldn’t be loaded because it is damaged or missing necessary resources. The bundle is damaged or missing necessary resources.
```

I have also tried both combinations with a MacPass build that I built from source myself, same result as well.

**Comment by mstarke** [comment]
That's strange. I will take a look.

**Comment by slovdahl** [comment]
Although it sounds far-fetched, it wouldn't surprise me too much if this too is caused by my case-sensitive macOS file system. 😕

**Comment by mstarke** [comment]
I can confirm the broken plugin with the current build. I'll take a look since this is something unexpected.

**Comment by greuff** [comment]
Any news? Same problem here. Workaround: I checked out commit 384796166ec88d688ad6da768dbe4492d1c00f86 from MacPassHTTP and built from source, that produced a working plugin for MacPass-continuous.

**Comment by mstarke** [comment]
No news, but your hint is a start, I tried to debug the problem but all the dynamic linking issues aren't my strong point. I did switch to a framework version of JSONModel which seems to have broken the plugins. I'll try to get this fixed ASAP. Sorry for the inconvenience.

**Comment by mstarke** [comment]
Found it. JSONModel.framework was not copied resulting in unresolved symbols. Current continuous build should work with continuous build of MacPass

**Comment by slovdahl** [comment]
Awesome, I just verified that it works. Thank you!
