### ISSUE TITLE
[Autotype] Defined Autotype is not saved permanently

### ISSUE THREAD

**Issue by cpne** [MacPass/MacPassHTTP#42]
Under 0.6.2 a defined Autotype with Window Title is not saved permanently.
After a reboot the defined Autotype is lost.

**Comment by mstarke** [comment]
This seems to be a MacPass issue? If so, please check if it works for the continuous release and if not, reopen the issue there.

**Comment by cpne** [comment]
I have the issue under Mac OS Sierra 10.12.5 (16F73).
I will check it after the next release.

**Comment by mstarke** [comment]
Can you test with this https://github.com/mstarke/MacPass/releases/tag/continuous release? It's the current development build.
