### ISSUE TITLE
MacPass crashes attempting to fill in username/password in chrome with chromeIPass

### ISSUE THREAD

**Issue by davzhou** [MacPass/MacPassHTTP#43]
I just installed the pre built macPass and macPassHttp continuous release on my macOS Sierra. I found macPassHttp in my plugins and was able to connect to the db from chromeIPass. I allow access from macPass and every time I go to a page with a recognized username/password field macPass crashes.

I checked my system log and found this.

com.apple.xpc.launchd[1] (com.apple.ReportCrash[1543]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash

**Comment by mstarke** [comment]
Will try to debug this. MacPassHTTP does not use XPC so this seems to be unrelated. You're running MacPass 0.7 continuous and MacPassHTTP 0.3 continuous?

**Comment by davzhou** [comment]
I am using MacPass 0.7 continuous. Not sure about MacPassHttp, how do I check that?

**Comment by mstarke** [comment]
Use Finder->Get Info on the Plugin. It should display 0.3 as Version then you're on continuous.

**Comment by davzhou** [comment]
Yes, I'm on 0.3

**Comment by mstarke** [comment]
I can reproduce the bug. Will try to fix it ASPA

**Comment by mstarke** [comment]
It's an issue with the resent JSONModel. I'm reverting back to an older release that's working.

**Comment by mstarke** [comment]
Current continuous release should work again.

**Comment by davzhou** [comment]
Got it working, thanks!
