### ISSUE TITLE
xcodebuild failed

### ISSUE THREAD

**Issue by allclay1993** [MacPass/MacPassHTTP#45]
The following build commands failed:
	CompileC build/MacPassHTTP.build/Release/MacPassHTTP.build/Objects-normal/x86_64/MPHServerDelegate.o MacPassHTTP/MPHServerDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by mstarke** [comment]
Can you provide a more detailed error log? Did you setup MacPassHTTP as described in the Readme?

**Comment by allclay1993** [comment]
How do I find an error log (command line noob here, sorry)? I followed the readme and got the above error. 

I just opened xcode and tried to build from there. In MPHMacPassHTTP.m it's giving errors on lines 48 and 49. (ignore the dots, I couldn't figure out how to indent)
`48     - (instancetype)initWithPluginHost:(MPPluginHost *)host {`
`.......................................^--------- Expected a type`
`49     self = [super initWithPluginHost:host];`
`...........^-----^-----------No visible @interface for 'MPPlugin' declares the selector 'initWithPluginHost:'`

**Comment by mstarke** [comment]
You seem to be missing the current source of MacPass since the plugin API did change. Try to use 0.7.x MacPass sources and it should work. Another option is to use the 0.3 release which is up to date and runs with MacPass 0.7.x

**Comment by allclay1993** [comment]
Ok, so how do I get the current source? I ran this to get what I have:
git clone https://github.com/mstarke/MacPass --recursive

Edit: nvm, I found it.

**Comment by mstarke** [comment]
Do you have the source in the lookup path?

**Comment by allclay1993** [comment]
Dumb question: what's a lookup path? Wish this was part of my computer science program haha

**Comment by allclay1993** [comment]
Thank you! I must have just had the wrong version. It shows up in the plugins list now.
