### ISSUE TITLE
How does it work ?

### ISSUE THREAD

**Issue by siddharthalodha** [MacPass/MacPassHTTP#46]
How do i get the AES key ? Trying to connect it to a alfred plugin.
Copied to the plugin folder. Shows up in Macpass. What next ? How do i generate the key ?

**Comment by mstarke** [comment]
The normal procedure is to request one from the plugin's http-server the a JSON request. Take a look at the official documentation for KeepassHTTP (https://github.com/pfn/keepasshttp#protocol) and you should be able to generate one yourself. If you're searching for UI to generate an arbitrary AES key, there is none and AFAIK the official plugin does not provide one neither.

**Comment by siddharthalodha** [comment]
It worked for me for the chrome plugin but for the alfred plugin, i am not able to work it out. Check the documentation on this link : https://github.com/samueldeng/alfred-keepass

It shows a KeePassHttp setting being generated inside the MacPass app. I can't seem to figure that out.

**Comment by mstarke** [comment]
What version of MacPass/MacPassHTTP are you using? If you're using a built from source or the continuous releases there is a UI change in MacPass. The "Custom" tab is missing and those fields are now below the tags box in the general tab. If you connected with Chrome plugin then you should already see the "KeePassHTTP Settings" entry in the root group.

![screen shot 2017-11-13 at 13 20 30](https://user-images.githubusercontent.com/58428/32725484-8f54bf80-c875-11e7-9c70-42132bc37cf0.png)

**Comment by mstarke** [comment]
Did that answer your questions?

**Comment by siddharthalodha** [comment]
Yes, It did. Thanks so much for the help.
