### ISSUE TITLE
Show only requests for existing / acknowledged entries

### ISSUE THREAD

**Issue by lenucksi** [MacPass/MacPassHTTP#5]
Currently MacPassHTTP either shows all requests made against it or none. 
All also shows the requests for domains for which no entry exists and generally leads to a lot of notification noise.
None might be too little information.

I would appreciate if only requests would be shown that successfully retrieve data (i.e. 200, no 404s).
The original KeePassHTTP shows the desired behaviour and could serve as an example.

**Comment by mstarke** [comment]
The current separation is that KeePassHTTPKit handles all low level communication and MacPassHTTP only implements the delegation. To support this behavior it's needed to flesh out the delegation or to let KeePassHTTPKit take care of the notifications. The former is the better approach as this is UI stuff and shouldn't be handled so low. I did not dive into all the details as there are still major tasks around plugins that need to be sorted out. This is a kind of test ballon. If you're up to it is love to see a pull request for this enhancement.

**Comment by mstarke** [comment]
Forget all the talk about delegation it was a simple check for matches and then suppressing the notification.

**Comment by lenucksi** [comment]
Yay. Sounds good. I've build the most recent version here and given it a try.
It mostly works, however from time to time there there are notifications with "de" entry not found.
It appears that the Firefox-Plugin checks for some pure tld entries. One may want to filter those as well.
