### ISSUE TITLE
Monochrome Icon for menu bar

### ISSUE THREAD

**Issue by mstarke** [MacPass/MacPassHTTP#50]
Use monochromatic icon instead of scaled down version of app icon.

This issue was moved from here: https://github.com/mstarke/MacPass/issues/727

**Comment by KyleSouth** [comment]
@mstarke,

I am excited for a monochromatic icon.  My MacPass icon is the one outlier on my desktop.

I don't know how monochromatic icon's are designed, so I have a question.  When you have a dark task bar, does the icon automatically invert itself, or do you have to have two icons for each style?

Example:
![2018-01-20_14-14-22 2](https://user-images.githubusercontent.com/7397241/35187681-3d03479e-fded-11e7-84b2-285174b61fef.png)
![2018-01-20_14-14-22](https://user-images.githubusercontent.com/7397241/35187682-4035c194-fded-11e7-993b-a3308a38c52b.png)

**Comment by berliozz** [comment]
If you need, I can create monochromatic icon in all sizes. That really looks ugly now.

**Comment by mstarke** [comment]
Thanks @berliozz for your support. This issue is marked as closed. The icon is added as a PDF but I've not come around for a new release to include it. I was holding this off until custom field support is working.

@KyleSouth the supplied icon is marked as template and will be rendered correctly on a dark and light menu bar.

![screen shot 2018-01-29 at 12 09 50](https://user-images.githubusercontent.com/58428/35507588-8b65c55e-04ed-11e8-8aa7-d7c5831b75ed.png)
![screen shot 2018-01-29 at 12 10 51](https://user-images.githubusercontent.com/58428/35507589-8b820520-04ed-11e8-9369-8d634346bce7.png)

**Comment by janjur** [comment]
Hi, so how can we switch to the monochromatic icon?
