### ISSUE TITLE
MacPassHTTP installation manual for dummies

### ISSUE THREAD

**Issue by jmgutierrezm** [MacPass/MacPassHTTP#52]
Hi All, is there anybody who has a MacPassHTTP installation manual for dummies?
I am absolute beginner and I have problems to install the plugin
Thanks in advance

**Comment by subic** [comment]
1. Install MacPass (continuous)
2. Download MacPassHTTP (https://github.com/MacPass/MacPassHTTP/releases/download/continuous/MacPassHTTP-continuous.zip)
3. Unzip
4. Move the MacPassHTTP.mpplugin file to ~/Library/Application Support/MacPass/ (press Command + Shift + G in Finder and paste the path if you cannot find the directory by yourself)
5. Restart MacPass. You should see MacPassHTTP in Preferences.../Plugins. If not check "Load unsecure plugins" and restart MacPass and it should work.
6. Use a browser add on to connect to MacPass - something like https://github.com/smorks/keepasshttp-connector, depending on your browser.

That's it, LMK if you get stuck somewhere...

**Comment by mstarke** [comment]
Actually, there have been some enhancements to this process (but not really big ones!) so an alternative is:

1. Install MacPass (continuous)
1. Download MacPassHTTP (https://github.com/MacPass/MacPassHTTP/releases/download/continuous/MacPassHTTP-continuous.zip)
1. Unzip
1. Start MacPass and open Preferences
1. Go to Plugins Section
1. Drag the MacPassHTTP.mplugin file on the left table
1. Restart MacPass by selecting it in the options
1. You should see MacPassHTTP in Preferences.../Plugins.
1. If the Plugin is displayed with an Alert icon check "Load unsecure Plugins" and restart MacPass again
6. Use a browser add on to connect to MacPass - something like https://github.com/smorks/keepasshttp-connector, depending on your browser.

If I can find the time I will finish what I started and users will be able to install plugins inside the Plugin prefefences.

**Comment by subic** [comment]
Even easier :) I've added the above post to the wiki under Installing MacPassHTTP.

**Comment by jmgutierrezm** [comment]
Hi subic and mstarke, I really appreciate your help!
I will try it and I will come back if any doubt remains

Thanks a lot!

**Comment by jmgutierrezm** [comment]
It works perfectly!
Thank you
