### ISSUE TITLE
MacPass hast disabled the Plugin - to Old - MacPass 0.7.9 (21570)

### ISSUE THREAD

**Issue by svalcken** [MacPass/MacPassHTTP#57]
MacPass hast disabled the Plugin - to Old - MacPass 0.7.9 (21570)

Message:
The Plugin is not compatible with the MacPass version (Translated from german MacPass)

**Comment by mstarke** [comment]
You should be able to use 0.3.1. It‘s available via the plugin browser.

**Comment by mstarke** [comment]
Were you able to resolve the issue?

**Comment by arnemoor** [comment]
I had the same problem. Enabling "Load unsecure Plugins"  in the settings, restarting, disabling the setting and restarting solved the issue for me.
