### ISSUE TITLE
Can't see the plugin in MacPass

### ISSUE THREAD

**Issue by Lich4r** [MacPass/MacPassHTTP#6]
Hi,

I build MacPassHTTP without any errors but I can't see it in MacPass plugin settings. 

What did I miss ? 

Thanks

**Comment by Lich4r** [comment]
Well after 3 reboot of the app the plugin is here and seems to work. However I don't know how to use it, when I visit a website I have a "Request for xx.com" and that's all.

**Comment by mstarke** [comment]
There was a Problem with GCDWebserver inside KeePassHTTPKit requiring address sanitizer to be present via the carthage build, this prevented any non-debug builds from loading the plugin because MacPass had address sanitizer enabled as well so the library was found only then. Hopefully this is now resolved.

**Comment by mstarke** [comment]
Can you elaborate what you mean by "I have a 'Request for xx.com' and that's all"

**Comment by Lich4r** [comment]
If I go to twitter.com for example and have MacPass open I will see this : 
<img width="331" alt="capture d ecran 2016-01-09 a 12 26 52" src="https://cloud.githubusercontent.com/assets/9169020/12215821/71451aec-b6cc-11e5-93fb-09e105ec8936.png">

If I click on it it brings MacPass on top of other windows but nothing more --> no autofill. I don't know how to allow the request

**Comment by Lich4r** [comment]
When using chromipass I got the allow access notification whereas passifox is allowed without my authorization. I can after do right click - fill in and logins are filled correctly. 
I think you can close it

**Comment by qwolf0** [comment]
I also had the issue where it took a few tries of re-launching MacPass for the plugin to appear. A bit of a noob on OSX; let me know if I can provide any logs to help. Thanks for your work!
