### ISSUE TITLE
Don't see option for plugins in MacPass Preferences

### ISSUE THREAD

**Issue by wonderweiner** [MacPass/MacPassHTTP#7]
Also, I downloaded the plugin, but don't have a folder at ~/Libary/Application Support/MacPass/MacPassHTTP.mpplugin to put it in. Am I missing something? Running the latest version, downloaded not built. Love where this program is headed, great development!

**Comment by mstarke** [comment]
MacPass only supports plugins in the github master branch, there is no binary release published that supports plugins. Furthermore macpass will create the folder for you (if it support plugins) and the folder isn't there already.

If you build MacPassHTTP and deploy it, you should get the folder too as it moves itself into this location, but there might be some issues.

**Comment by wonderweiner** [comment]
Great thanks!
