### ISSUE TITLE
Why there is no pre-build binary

### ISSUE THREAD

**Issue by orhanveli** [MacPass/MacPassHTTP#9]
Please provide a pre-build binary!

**Comment by mstarke** [comment]
Going to happen but currently useless until there's a MacPass binary capable of loading plugins.

**Comment by callumgare** [comment]
Now that there is a MacPass binary capable of loading plugins is a MacPassHTTP binary on the way? Sorry to be pushy, I've just excited about the prospect of being able to use MacPass+KeePassHTTP without needing to compile for years now.
Cheers :+1:

**Comment by ritzmann** [comment]
That would be great to have. I just upgraded to MacPass 0.6 and then went on a search for the matching compiled plugin.
